### ISSUE TITLE
GDPR compliance

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/WP8-Documents#1]
It must be ensured that pan-learning.org is GDPR compliant. To this end ELI has developed a bespoke [Data Protention Information document](https://github.com/pan-training/pan-learning-djangotools/files/6500502/Panosc._.data.protection.information.pdf) that users who sign up (and existing users) need to acknowledge that they have read and agree to.  The following sub-tasks are therefore defined:

- [x] Review document to ensure once more that the platform conforms to the document -> @moving-northwards 
- [x] Setup pan-learning.org so that people signing up needs to acknowledge that they have read the information document before they get access -> @willend 
- [x] Add the document to the pan-learning repo so that it becomes editable but cannot be linked to production site without proper approval by pan-learning.org management. Do this by creating a new repo for documents -> @moving-northwards 
- [x] Make the document easily accessible to users at all times, e.g. link in the footer -> @moving-northwards 
- [x]  Find out if we need to ensure that existing users acknowledge that they have read the document -> @teodorivanoaica 
- [x] Get existing users to agree to the GDPR. Can we do this by sending an email where no response is interpreted as an acknowledgement? @moving-northwards @willend @teodorivanoaica

**Comment by thomasholmrod** [comment]
@teodorivanoaica can you give an update on this?

**Comment by teodorivanoaica** [comment]
GDPR will information like a pop-up prompt box displaying the GDPR information with the option to acknowledge.
We will look into moodle tools to see if this kind of pop-up prompt boxes is available in Moodle.

**Comment by moving-northwards** [comment]
@teodorivanoaica @thomasholmrod  Please can you take a look at my pull request to update the GDPR document?

**Comment by willend** [comment]
I found the relevant setting in Moodle, under https://pan-learning.org/moodle/admin/settings.php?section=policysettings

- non-admin users are now prompted for acceptance on login

**Comment by willend** [comment]
(I guess the last point means that we could in fact close this issue @thomasholmrod @teodorivanoaica @moving-northwards)

**Comment by teodorivanoaica** [comment]
I can't login... but that solves the GDPR problem.

**Comment by thomasholmrod** [comment]
@moving-northwards can you please check that it works: 

1. 1st time you log in as non-admin user, you are enforced to acknowledge that you have read the gdpr doc
2. 2nd and 3rd time you can just login as usual as a non-admin user

**Comment by moving-northwards** [comment]
I've already checked - it does work!

**Comment by thomasholmrod** [comment]
cool

**Comment by willend** [comment]
@teodorivanoaica just saw there is in fact a small PR (mainly spelling etc. from our native English-speaker @moving-northwards) above. - But nothing that changes the fundamental meaning of the GDPR doc. Can you have a look? :)

**Comment by moving-northwards** [comment]
@teodorivanoaica  Please could you take a look at the pull request.

**Comment by moving-northwards** [comment]
GDPR pdf document has been updated and can be found at https://pan-learning.org/moodle/customfiles/DataProtectionInformation
