### ISSUE TITLE
Joint expands - panosc training landing page

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/WP8-Documents#9]
Create joint landing page for training catalogue and e-elearning platform using pan-training.github.io to begin with

**Comment by thomasholmrod** [comment]
as discussed at today's WP5 ExPaNDS / WP8 PaNOSC meeting

**Comment by moving-northwards** [comment]
Why do we want to create a whole new landing page when we just removed one? Is it not OK to provide a link to the training catalogue from the e-learning platform (which now has a home page you don't need to sign in to see?)

**Comment by knodel** [comment]
Both systems are more or less equivalent and with a joint landing page we can show that in both projects individual systems were developed and brought together in a common portal. At the moment my argumentation in our deliverable is something like this:

> One major question in developing a common portal is how potential future users interact with our portal to find, access and provide training material. On the level of the portal itself it should be clear that our approach is divided into two complementary parts:

>•	A training catalogue where (external) material is provided  and
•	An e-learning platform with (internal) blended learning courses.

> Therefore, it is essential to provide these different facets on a common PaN portal or landing page to guide our PaN scientists and further interested groups directly to the resource they expect. Furthermore it is necessary to forward users to the other system by linking re-sources at certain points where it is appropriate.

And the third component from Thibauds slides is the **Training Events calendar**. But I'm not sure if that is still up-to-date or a component of the catalogue.

**Comment by knodel** [comment]
We can also try to integrate the link to our catalogue on the front-page of the e-learning platform, but then we should present it in a way that the visitor realizes that there are two systems with slightly different focus and use-cases. That should also be possible 🤔

**Comment by moving-northwards** [comment]
OK I see now what his should be. 

Should this page then have a separate domain name to pan-learning and pan-training since it is a sort of overarching page which presents the two as a choice to users. I notice the task asks to use pan-training.github.io to begin with - I guess it is up for discussion. 

I can already add a link to advertise pan-training.hzdr.de on pan-learning.org in a side box with a little blurb so users can go and have a look.  

I will start creating this landing page then.

**Comment by knodel** [comment]
Sounds good 👍🏻. On pan-training.hzdr.de I'll add also a separate link to pan-learning.org in our header.

**Comment by thomasholmrod** [comment]
We decided to use either pan-learning.org or pan-training.org as the overall domain name, but for now just go with pan-training.github.io 

the domain names for the sub-services can then be catalogue.pan-training.... and e-learning.pan-training.... and events.pan-training... and so on or just pan-training.github.io/catalogue etc

**Comment by thomasholmrod** [comment]
Why not use the training catalogue as landing page and add pan-learning.org as a menu there?

**Comment by knodel** [comment]
I added an additional tile "PaN-learning" on the catalogue's front page at https://pan-training.hzdr.de 
@thomasholmrod @moving-northwards

**Comment by moving-northwards** [comment]
I will close this issue as we have made some progress on this and new issues will take its place.
